name: Master

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:

  tests:
    # Only one OS is required since fmt is cross platform
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Deno
        uses: denoland/setup-deno@v1

      - name: Run tests
        run: |
          deno task test:install
          deno task test:build
          deno task test:start


  code_quality:
    # Only one OS is required since fmt is cross platform
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Deno
        uses: denoland/setup-deno@v1

      - name: Check `deno lint` passes
        run: deno lint

      - name: Check `deno fmt` passes
        run: deno fmt --check
